### ISSUE TITLE
Reduce Number of Screws

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensor3dPrintableCase#1]
Choose a minimum of total screws as well as a minimum of different types. If possible, choose screws that are widely available (hardware store, etc.).

**Comment by opatut** [comment]
The current version takes only M3x8 screws and a single M3x18 screw (I think) for the locking pin. There is still a need for corresponding nuts and heatset inserts, but this is way better than before. No more M3x45 screws, which are useless for any other project and not included in the ususal amazon M3 bolt collection packages etc. ;)

I think we can close this.
