### ISSUE TITLE
Add loops for a little string to attach the pin to the main case

### ISSUE THREAD

**Issue by opatut** [openbikesensor/OpenBikeSensor3dPrintableCase#15]
A little hole in the pin, and one in a fitting location on the main case, would allow me to attach the pin with a string to the main body and never lose one _again_ ;)

**Comment by gluap** [comment]
I just noticed that the pin already has a fitting hole. The string can be wound around one of the case screws on the case side to provide the requested functionality.

**Comment by opatut** [comment]
Done, at least on `openscad` branch.
