### ISSUE TITLE
OBS-Display-A-005_Kabelbinder_Schiene_v0.1.0: Change Side of the Magnet-Pocket

### ISSUE THREAD

**Issue by Carolinitzny** [openbikesensor/OpenBikeSensor3dPrintableCase#17]
The Magnet-Pocket is on the upper side in build direction, where the printer has to bridge. This is prone to inaccuracy and therefore makes putting the second magnet in very hard (if the printing wasn't as clean :)  ).
Would be nice, if the magnet-pocket is on the other side where the bridging is more accessible and easier to clean up.

**Comment by tobst** [comment]
This part has been bothering me since i designed it. I would be happy to redesign. Can you provide a simple sketch to clarify your suggestion?

**Comment by Carolinitzny** [comment]
![image](https://user-images.githubusercontent.com/7027740/120929004-8a010600-c6e7-11eb-8209-89753de6835b.png)
The light green part is for the handlebar, the darker green is the part where the magnets fit in

**Comment by opatut** [comment]
Hi @Carolinitzny, your suggestion was applied on the `openscad` branch at least, maybe even before in the legacy files.

![image](https://user-images.githubusercontent.com/235784/149662651-c6c5b542-d829-43e5-9ef6-7c097c65a476.png)
