### ISSUE TITLE
Include a hole under magnet housing to be able to slide magnets out of their housing

### ISSUE THREAD

**Issue by rotger711** [openbikesensor/OpenBikeSensor3dPrintableCase#2]
In this version it is not possible to get the two magnets out of their housing. With a hole in the middle under the magnet housing this is made possible. Necessary if two OBS systems and sliding fixture are exchanged with opposite magnet (south / north) orientation.

**Comment by opatut** [comment]
We're talking about the display rail here, I think. A hole was added long ago and it is also present in the `openscad` version.
