### ISSUE TITLE
Welche Dateien sind die richtigen?

### ISSUE THREAD

**Issue by derlucas** [openbikesensor/OpenBikeSensor3dPrintableCase#20]
Hallo Zusammen,
aus der Doku https://www.openbikesensor.org/docs/hardware/general/case/ geht nicht hervor, welche Dateien man drucken muss.

Ich habe dem Rat entsprechend das Vertical Case gewählt und stehe vor der Frage OBS-MainCase A B C D?

Eine kurze Aufstellung der Files für ein Gehäuse samt Halterung an der Sattelstütze wäre irgendwie ganz hilfreich.

Grüße
Lucas

**Comment by opatut** [comment]
[Dieser PR](https://github.com/openbikesensor/openbikesensor.github.io/pull/95) wird das vermutlich lösen.

**Comment by SubOptimal** [comment]
Du kannst auch das Release Archiv herunterladen. Die Dateien sind für den OpenBikeSensor v00.03.12.

https://github.com/openbikesensor/OpenBikeSensor3dPrintableCase/releases/tag/v0.1.0

**Comment by opatut** [comment]
Noch besser wird das ab sofort von https://github.com/openbikesensor/openbikesensor.github.io/pull/129 abgedeckt. Ich schließe mal dieses Ticket.
