### ISSUE TITLE
Add loop for safety strap on main case

### ISSUE THREAD

**Issue by gluap** [openbikesensor/OpenBikeSensor3dPrintableCase#21]
The holding bracket of several of our OBS broke while the driver was cycling on rough ground. So far in all cases the OBS and the Bike suffered no permanent damage. The broken parts were printed by different people, with different filaments (DasFilament PETG and Tinmorry PETG) and high infill percentage in the affected area. I have created a modified bracket (attached) to reduce likelihood of this happening. Furthermore I changed the printing direction such that the layers are now parallel to the direction of the stresses in the area ("printed sideways"). The broken brackets (of the vanilla variant from the repo) were already printed with 100% infill in the affected area.

Without a safety strap on the case, a broken bracket may always result in the OBS falling into the back wheel causing the driver to fall, resulting in injury and a potentially damaged bike. To avoid this risk I imagine one could have a loop to attach a safety strap that to be secured against the seatpost. 

<img src="https://user-images.githubusercontent.com/44007906/135156488-0292ccb2-523b-44bf-b7db-36bfb65fb71e.jpeg" width=200>

[strengthened mount.zip](https://github.com/openbikesensor/OpenBikeSensor3dPrintableCase/files/7246949/strengthened.mount.zip)

A minimalist way to attach a strap could look like this, with the strap running through the grove shown in green: 
<img src="https://user-images.githubusercontent.com/44007906/135160296-5b149660-c8e2-4714-ae0e-e8e6a0756497.png" width=200>
[strap_braket.zip](https://github.com/openbikesensor/OpenBikeSensor3dPrintableCase/files/7247056/strap_braket.zip)

**Comment by gluap** [comment]
[strengthened mount.zip](https://github.com/openbikesensor/OpenBikeSensor3dPrintableCase/files/7246949/strengthened.mount.zip)

**Comment by gluap** [comment]
I printed a few of the thicker brakets with the simple strap clamp shown above to test them.

<img src="https://user-images.githubusercontent.com/44007906/135335294-54c97920-9e79-4531-b941-833767e48da0.jpg" width="400">

**Comment by Ventusfahrer** [comment]
Hi,

I would also suggest to move the chamber more to the top. 

![Klammeroptimierung](https://user-images.githubusercontent.com/5901190/143504481-4fdf3ae9-0838-4437-96e6-20aab98347e4.jpg)

Despite the current increase of the outer parts of the brackets the critical part is still unchanged (with standard slicer settings 2 outer shells and one for the inner one of the chamber). The critical part is the red marked part of the structure. Here  we have a high drag. At the right border we have pressure and in the middle nearly no force.

Moving the chamber more (or better as most as possible) to the right will move it more to the neutral line and create a higher wall thickness of the most stressed part. 

On the other hand: I strongly support the exchange the standard OBS mount part with the one proposed in this change (may be with my additional proposal)
