### ISSUE TITLE
change OBS holding device

### ISSUE THREAD

**Issue by mega-stoffel** [openbikesensor/OpenBikeSensor3dPrintableCase#3]
The current OBS holding device has a gap in it to keep the holding screw. I'd suggest to make this gap over the whole width of this device.
The advantage would be, to be able to turn the holding device around and mount the OBS in a tilted position. I hope, to get a better GPS position, if the OPS is not looking directly into my body, but a bit more into the clear sky.

**Comment by opatut** [comment]
It has been mirrored to the other side for a while now.
