### ISSUE TITLE
OpenSCAD: parameter "UsbPort_clearance" is not used

### ISSUE THREAD

**Issue by KlausMu** [openbikesensor/OpenBikeSensor3dPrintableCase#38]
I guess this parameter should be used in "MainCase.scad", but there you find hardcoded "UsbCoverMainBody(clearance=0.15)". Currently it is not used anywhere.

**Comment by opatut** [comment]
Thanks for the hint. I noticed this myself while refactoring all variable names, so it's gone. 

Good catch on the hardcoded value, I've now named it `MainCase_usb_port_cover_clearance` and set it to `default_clearance` in the variables file, so you can override it if you need more clearance for a good fit on that part only.
