### ISSUE TITLE
New OpenSCAD designs lack bridge helpers

### ISSUE THREAD

**Issue by codingcatgirl** [openbikesensor/OpenBikeSensor3dPrintableCase#48]
I love that you converted everything to OpenSCAD and cleaned up the repo, really awesome!

However, the new versions can't be printed without supports because bridge helpers are missing in crucial places. I've attached two examples where bridging helpers would be needed. This definitely confuses me because in `variables.scad` there's an `enable_easy_print` option which sounds like it should add bridge helpers but it looks like it doesn't, at least not in these places?

I've attached two pictures showing areas with issues and two pictures of the bridge helpers in the old version of the case for reference.

![MainCase](https://user-images.githubusercontent.com/3868507/155115793-4cb90343-cfa2-4d2f-85be-a0db6805b733.png)
![MainCase2](https://user-images.githubusercontent.com/3868507/155115796-a98fa15a-d691-4904-8a15-f680ff4045a3.png)
![Bildschirmfoto von 2022-02-22 11-42-39](https://user-images.githubusercontent.com/3868507/155116479-4ce5411f-847a-4c21-9361-d06b178b81a3.png)
![Bildschirmfoto von 2022-02-22 11-43-01](https://user-images.githubusercontent.com/3868507/155116474-fadf7896-84cd-4ce6-a9b6-57461f358127.png)

**Comment by codingcatgirl** [comment]
Was just about to submit a pull request, then noticed it's fixed in #47 :) Cool, i'll just use that branch then.

**Comment by codingcatgirl** [comment]
It is also fixed for the switch, however at the GPS hole there is still a t-shaped bridge left. Not that big a deal, but probably good to fix as well :)

**Comment by gluap** [comment]
@codingcatgirl So the below screenshot is the problematic bridge, right?

To avoid double work: are you looking into it? Otherwise I'd see that I do it later.

If you are in a hurry: For me that corner wasn't beautiful but didn_t look it had structural problems either.

![image](https://user-images.githubusercontent.com/44007906/155144924-3b7453f4-fd4f-46ec-a7de-4fa81323f87d.png)

**Comment by codingcatgirl** [comment]
Hey! No, i'm not looking into it right now. This one could be easily fixed by SuperSlicer's bridging features. And even if it wasn't, since it's on the inside it would have bothered me less. :)
