### ISSUE TITLE
Curved bridging since latest commits

### ISSUE THREAD

**Issue by codingcatgirl** [openbikesensor/OpenBikeSensor3dPrintableCase#55]
One of the bridge helpers at the switch port has a curved perimeter, which is not ideal and defeats the purpose a bit :)

![Bildschirmfoto von 2022-02-28 20-12-16](https://user-images.githubusercontent.com/3868507/156044372-dc356ad2-0745-4c7e-9745-1ae817ab8db1.png)

**Comment by gluap** [comment]
I take this to mean "I expected an octagonal final layer of bridge helpers", is that right? 
I stopped at a square like we had in the original design (below).

![image](https://user-images.githubusercontent.com/44007906/156055411-7470fabb-52b0-45c4-968f-3fa32c1f0310.png)

**Comment by codingcatgirl** [comment]
no, i specifically mean the curved perimeter aliend with the outside shape of the case (top right corner) :) That wasn't like that a few days ago i think.

**Comment by gluap** [comment]
I added the chage to the beta branch, it should now not be curved any more. This is what it looks sliced for me in the beta version.
![image](https://user-images.githubusercontent.com/44007906/156150604-db487df1-6c64-4397-b922-b102ae5a29dd.png)

**Comment by codingcatgirl** [comment]
Sounds great. I would recommend merging it soon since i get quite a bit of a mess in this section of the part without the fix.

**Comment by gluap** [comment]
It is already available [here](https://github.com/openbikesensor/OpenBikeSensor3dPrintableCase/tree/beta) - I also have a printed version that goes together, but to avoid issues with non-fitting PCBs in the future I'd rather wait until the first one of these has been built successfully (with the PCB 0.03.12, which I don't have yet.).

**Comment by codingcatgirl** [comment]
With my slicing settings it looks much worse with the curve. I might have to look into that. Anyway, yes i know it's on the beta branch, it's what i'm currently printing :)

**Comment by gluap** [comment]
I merged the fix to main with the latest merge from beta now that there are several cases out there with the fix.
