### ISSUE TITLE
Etwas mehr Platz im Display-Deckel für den Stecker 

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensor3dPrintableCase#69]
Wie beim Treffen in Stuttgart u.a. mit @gluap besprochen, sollten wir etwas mehr Platz im Display-Deckel für den Stecker schaffen.

**Comment by gluap** [comment]
Ist das nicht in latest schon drin?

**Comment by gluap** [comment]
Nvm: es ist noch mehr Platz den wir nutzen wollten

**Comment by gluap** [comment]
Ist jetzt dabei!
