### ISSUE TITLE
GPS Antennenposition

### ISSUE THREAD

**Issue by Steffeng5** [openbikesensor/OpenBikeSensor3dPrintableCase#7]
wegen 3D Druck Präzisionsproblemen könnte die Antenne fürs GPS auch von oben eingeführt werden, da diese ja sowieso mit einer Deckplatte abgedeckt wird. So ist es nicht zwingend nötig auf Zehntel Millimeter genau zu drucken

**Comment by mdoersam** [comment]
Wäre es ok, dann die Möglichkeit, das Gehäuse an der Stelle zu montieren komplett zu entfernen? Nach unserem Gespräch heute war das ja anscheinend sowieso nicht mehr der Fall

**Comment by opatut** [comment]
Das wurde längst umgesetzt :tada:
