### ISSUE TITLE
DisplayParts in VerticalCase Directory

### ISSUE THREAD

**Issue by Steffeng5** [openbikesensor/OpenBikeSensor3dPrintableCase#8]
There are display mount parts in /MainCase/VerticalCase/. By mistake I think?

**Comment by mdoersam** [comment]
Can you list the filenames for easier confirmation?

**Comment by Steffeng5** [comment]
OBS-A-001-AlternativeMount22mmSlide.stl
OBS-A-002-AlternativeMount22mmTop.stl
OBS-A-003-AlternativeMount22mmBottom.stl
