### ISSUE TITLE
Add One Layer to "with LED holes" variant

### ISSUE THREAD

**Issue by Steffeng5** [openbikesensor/OpenBikeSensor3dPrintableCase#9]
For better water resistance there should maybe one 0.2mm layer to cover the LED holes. This should be thin enough to see the leds but protect against rain.

**Comment by mdoersam** [comment]
Not sure how needed this might be. 
Plan A is to add hot glue to plug the holes and have it transparent.
Plan B could be to just add a small modifier in the Slicer and have your effect if someome doesn't want to go the hotglue-route

**Comment by opatut** [comment]
Superseded by #35.
